import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    maxWidth: "1000px",
    margin: "40px auto",
    fontFamily: "sans-serif",
    padding: "0 16px",
  },
  title: { marginBottom: "8px" },
  status: { marginBottom: "16px", color: "#555" },
  twoColumns: {
    display: "flex",
    flexDirection: "row",
    gap: "24px",
    flexWrap: "wrap",
  },
  panel: {
    flex: "1 1 400px",
    minWidth: "280px",
    padding: "16px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    background: "#fafafa",
  },
  panelTitle: {
    marginTop: 0,
    marginBottom: "12px",
    fontSize: "18px",
  },
  traceRow: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: "12px",
    marginTop: "16px",
    marginBottom: "12px",
  },
  traceVerify: {
    padding: "8px 12px",
    fontSize: "13px",
    background: "#f5f5f5",
    borderRadius: "4px",
    wordBreak: "break-all",
  },
  traceId: { fontSize: "12px", userSelect: "all" },
  inputRow: { display: "flex", gap: "8px", marginBottom: "8px" },
  idRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "8px",
  },
  idLabel: {
    fontSize: "14px",
    fontWeight: "bold",
    minWidth: "24px",
  },
  idInput: {
    flex: 1,
    padding: "6px 10px",
    fontSize: "14px",
    border: "1px solid #ccc",
    borderRadius: "4px",
  },
  buttonRow: {
    display: "flex",
    gap: "8px",
    marginBottom: "12px",
    flexWrap: "wrap",
  },
  input: {
    flex: 1,
    padding: "8px 12px",
    fontSize: "16px",
    border: "1px solid #ccc",
    borderRadius: "4px",
  },
  button: {
    padding: "8px 16px",
    fontSize: "14px",
    backgroundColor: "#4f46e5",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  buttonSecondary: {
    backgroundColor: "#0d9488",
  },
  buttonTertiary: {
    backgroundColor: "#b45309",
  },
  buttonMongo: {
    backgroundColor: "#6b21a8",
  },
  traceFlow: {
    marginTop: "12px",
    padding: "8px 10px",
    fontSize: "12px",
    background: "#eee",
    borderRadius: "4px",
    borderLeft: "3px solid #4f46e5",
  },
  traceFlowLabel: {
    fontWeight: "bold",
    marginRight: "6px",
  },
  traceFlowPath: {
    color: "#333",
  },
  resultsSection: {
    marginTop: "24px",
    padding: "16px",
    border: "1px solid #ccc",
    borderRadius: "8px",
    background: "#f9f9f9",
  },
  resultsTitle: {
    marginTop: 0,
    marginBottom: "10px",
    fontSize: "14px",
    color: "#555",
    fontWeight: "bold",
  },
  resultsTextarea: {
    width: "100%",
    height: "260px",
    padding: "8px 12px",
    fontSize: "14px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    resize: "vertical",
    boxSizing: "border-box",
  },
};
