apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    app.kubernetes.io/component: grafana
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://{{ .Release.Name }}-tempo:3200
        isDefault: true
        editable: true
