apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8088
          env:
            - name: NATS_URL
              value: {{ .Values.api.env.NATS_URL | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.api.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_INSTRUMENTATION_GO_TRACING_ENABLED
              value: {{ .Values.api.env.OTEL_INSTRUMENTATION_GO_TRACING_ENABLED | quote }}
            - name: OTEL_MONGO_TRACING_ENABLED
              value: {{ .Values.api.env.OTEL_MONGO_TRACING_ENABLED | quote }}
            - name: OTEL_MONGO_PROPAGATION_ENABLED
              value: {{ .Values.api.env.OTEL_MONGO_PROPAGATION_ENABLED | quote }}
            - name: OTEL_NATS_TRACING_ENABLED
              value: {{ .Values.api.env.OTEL_NATS_TRACING_ENABLED | quote }}
            - name: OTEL_GORILLA_WS_TRACING_ENABLED
              value: {{ .Values.api.env.OTEL_GORILLA_WS_TRACING_ENABLED | quote }}
