apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8088
            - containerPort: 6060
              name: pprof
          env:
            - name: NATS_URL
              value: {{ .Values.api.env.NATS_URL | quote }}
            - name: MONGODB_URI
              value: {{ .Values.api.env.MONGODB_URI | quote }}
            - name: WORKER_URL
              value: {{ .Values.api.env.WORKER_URL | quote }}
            {{- include "otel-traces-test.otelEnv" .Values.api.env | nindent 12 }}
