apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - containerPort: 8082
            - containerPort: 6060
              name: pprof
          env:
            - name: NATS_URL
              value: {{ .Values.worker.env.NATS_URL | quote }}
            - name: MONGODB_URI
              value: {{ .Values.worker.env.MONGODB_URI | quote }}
            {{- include "otel-traces-test.otelEnv" .Values.worker.env | nindent 12 }}
