apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          ports:
            - containerPort: 8082
          env:
            - name: NATS_URL
              value: {{ .Values.worker.env.NATS_URL | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.worker.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_INSTRUMENTATION_GO_TRACING_ENABLED
              value: {{ .Values.worker.env.OTEL_INSTRUMENTATION_GO_TRACING_ENABLED | quote }}
            - name: OTEL_MONGO_TRACING_ENABLED
              value: {{ .Values.worker.env.OTEL_MONGO_TRACING_ENABLED | quote }}
            - name: OTEL_MONGO_PROPAGATION_ENABLED
              value: {{ .Values.worker.env.OTEL_MONGO_PROPAGATION_ENABLED | quote }}
            - name: OTEL_NATS_TRACING_ENABLED
              value: {{ .Values.worker.env.OTEL_NATS_TRACING_ENABLED | quote }}
            - name: OTEL_GORILLA_WS_TRACING_ENABLED
              value: {{ .Values.worker.env.OTEL_GORILLA_WS_TRACING_ENABLED | quote }}
