apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.nodePorts.api }}
  selector:
    app: api
