apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker-pprof
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - name: pprof
      port: 6060
      targetPort: 6060
